### ISSUE TITLE
generating synthetic data

### ISSUE THREAD

**Issue by shumailaahmed** [totti0223/crop_seed_instance_segmentation#1]
your paper was a great read, I am wondering if you have open-sourced your synthetic data generation pipeline, I am working on a similar segmentation task in the radiogenomics domain, and wondering if I can use your synthetic data generation methodology. TIA

**Comment by totti0223** [comment]
thx
planning to create a new repository "soon" but human resource is extremely limited now....
contact me via mail and depending on the situation maybe I can share you the codes
